# Docker Swarm stack: HA PHP+NGINX+MariaDB with Caddy

services:
  # Caddy: HTTP reverse proxy and load balancer
  caddy:
    image: caddy:2
    ports:
      - "80:80"   # Accept HTTP traffic
    configs:
      - source: caddyfile   # Mount Caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - ha_overlay
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure

  # MariaDB: single database service
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: ha-app-db:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
    networks:
      ha_overlay:
        aliases:
          - ha_stack_db
          - db
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p${DB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Web: PHP+NGINX tier with autoscaling (min 2, max 6)
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: ha-app-web:latest
    environment:
      - DB_HOST=ha_stack_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    depends_on:
      - db
      - caddy
    networks:
      - ha_overlay
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "swarm.autoscaler=true"
        - "swarm.autoscaler.minimum=2"
        - "swarm.autoscaler.maximum=4"
      restart_policy:
        condition: on-failure
      resources:
        reservations:   # Guaranteed at all times
          cpus: "0.10"      # 0.10 vCPU * 4 = 0.4 vCPU reserved
          memory: 200M      #  200   MB * 4 = 0.8 GB   reserved
        limits:         # Maximum burst per container
          cpus: "0.22"      # 0.22 vCPU * 4 = 0.88 vCPU total
          memory: 400M      #  400   MB * 4 = 1.6  GB   total
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health"]
      interval: 10s
      timeout: 2s
      retries: 3

# Mount Caddyfile
configs:
  caddyfile:
    file: ./config/caddy/Caddyfile

# Persistent volume for MariaDB
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/ha_db
      o: bind

# Overlay network (created by run.sh)
networks:
  ha_overlay:
    driver: overlay
