# Docker Swarm stack: HA PHP+NGINX+MariaDB with Caddy

services:
  # Caddy: HTTP reverse proxy and load balancer
  caddy:
    image: caddy:2
    ports:
      - "80:80"     # Accept traffic
    configs:
      - source: caddyfile   # Mount Caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - ha_overlay
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure

  # MariaDB: single database service
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: ha-app-db:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
    networks:
      ha_overlay:
        aliases:
          - ha_stack_db
          - db
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p${DB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Web: PHP+NGINX tier with 3 replicas
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: ha-app-web:latest
    environment:
      - DB_HOST=ha_stack_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    depends_on:
      - db
      - caddy
    networks:
      - ha_overlay
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health"]
      interval: 10s
      timeout: 2s
      retries: 3

# Mount Caddyfile
configs:
  caddyfile:
    file: ./config/caddy/Caddyfile

# Persistent volume for MariaDB
volumes:
  mariadb_data:
    external: true
    name: mariadb_data

# Overlay network (created by run.sh)
networks:
  ha_overlay:
    driver: overlay
